#!/usr/bin/env python3
"""
Generate data/apps_list.json from the master 499 app list.
Each entry: id, name, slug, category, subcategory, search_keywords
"""
import json, os, re

APPS = [
    # ===== 1. PHIM NHẠC & STREAMING (50 app) =====
    (1, "YouTube ReVanced", "streaming", ""),
    (2, "Spotify Premium Mod", "streaming", ""),
    (3, "TikTok Mod", "streaming", ""),
    (4, "Netflix Mod", "streaming", ""),
    (5, "SoundCloud Mod", "streaming", ""),
    (6, "Deezer Premium Mod", "streaming", ""),
    (7, "Tidal HiFi Mod", "streaming", ""),
    (8, "Apple Music Mod", "streaming", ""),
    (9, "Joox VIP Mod", "streaming", ""),
    (10, "Zing MP3 Premium Mod", "streaming", ""),
    (11, "Nhaccuatui VIP Mod", "streaming", ""),
    (12, "Pandora Premium Mod", "streaming", ""),
    (13, "Audible Premium Mod", "streaming", ""),
    (14, "FilmPlus Mod", "streaming", ""),
    (15, "Cinema HD Mod", "streaming", ""),
    (16, "BeeTV Mod", "streaming", ""),
    (17, "Stremio Mod", "streaming", ""),
    (18, "Kodi Mod", "streaming", ""),
    (19, "Live NetTV Mod", "streaming", ""),
    (20, "HBO Max Mod", "streaming", ""),
    (21, "Disney+ Mod", "streaming", ""),
    (22, "Prime Video Mod", "streaming", ""),
    (23, "Hulu Mod", "streaming", ""),
    (24, "Peacock TV Mod", "streaming", ""),
    (25, "Paramount+ Mod", "streaming", ""),
    (26, "Crunchyroll Mod", "streaming", ""),
    (27, "Funimation Mod", "streaming", ""),
    (28, "Viki Mod", "streaming", ""),
    (29, "iQIYI Mod", "streaming", ""),
    (30, "WeTV Mod", "streaming", ""),
    (31, "Viu Mod", "streaming", ""),
    (32, "MangoTV Mod", "streaming", ""),
    (33, "Tencent Video Mod", "streaming", ""),
    (34, "Youku Mod", "streaming", ""),
    (35, "Bilibili Mod", "streaming", ""),
    (36, "Twitch Mod", "streaming", ""),
    (37, "TikTok Lite Mod", "streaming", ""),
    (38, "Likee Mod", "streaming", ""),
    (39, "SnackVideo Mod", "streaming", ""),
    (40, "MxPlayer Pro Mod", "streaming", ""),
    (41, "VLC Pro Mod", "streaming", ""),
    (42, "nPlayer Plus Mod", "streaming", ""),
    (43, "KMPlayer Premium Mod", "streaming", ""),
    (44, "PotPlayer Mod", "streaming", ""),
    (45, "Plex Mod", "streaming", ""),
    (46, "Jellyfin Mod", "streaming", ""),
    (47, "Emby Premiere Mod", "streaming", ""),
    (48, "Spotify Lite Mod", "streaming", ""),
    (49, "YouTube Music ReVanced", "streaming", ""),
    (50, "SoundCloud Go+ Mod", "streaming", ""),

    # ===== 2. CHỈNH SỬA ẢNH & VIDEO (50 app) =====
    (51, "CapCut Pro Mod", "photo_video", ""),
    (52, "Adobe Lightroom Premium Mod", "photo_video", ""),
    (53, "PicsArt Gold Mod", "photo_video", ""),
    (54, "VSCO Premium Mod", "photo_video", ""),
    (55, "Snapseed Pro Mod", "photo_video", ""),
    (56, "FaceApp Pro Mod", "photo_video", ""),
    (57, "Remini Mod", "photo_video", ""),
    (58, "YouCam Perfect Mod", "photo_video", ""),
    (59, "AirBrush Pro Mod", "photo_video", ""),
    (60, "Facetune Mod", "photo_video", ""),
    (61, "B612 Mod", "photo_video", ""),
    (62, "Snow Mod", "photo_video", ""),
    (63, "Ulike Mod", "photo_video", ""),
    (64, "Meitu Mod", "photo_video", ""),
    (65, "Perfect365 Mod", "photo_video", ""),
    (66, "KineMaster Diamond Mod", "photo_video", ""),
    (67, "PowerDirector Premium Mod", "photo_video", ""),
    (68, "FilmoraGo Pro Mod", "photo_video", ""),
    (69, "InShot Pro Mod", "photo_video", ""),
    (70, "VivaVideo Pro Mod", "photo_video", ""),
    (71, "Alight Motion Pro Mod", "photo_video", ""),
    (72, "Motion Ninja Pro Mod", "photo_video", ""),
    (73, "VN Video Editor Mod", "photo_video", ""),
    (74, "Canva Pro Mod", "photo_video", ""),
    (75, "Adobe Express Premium Mod", "photo_video", ""),
    (76, "Prequel Premium Mod", "photo_video", ""),
    (77, "GlitchVideo Pro Mod", "photo_video", ""),
    (78, "Unfold Mod", "photo_video", ""),
    (79, "Mojo Pro Mod", "photo_video", ""),
    (80, "StoryChic VIP Mod", "photo_video", ""),
    (81, "PhotoRoom Pro Mod", "photo_video", ""),
    (82, "Background Eraser Pro Mod", "photo_video", ""),
    (83, "TouchRetouch Pro Mod", "photo_video", ""),
    (84, "Pixlr Premium Mod", "photo_video", ""),
    (85, "Fotor Photo Editor Mod", "photo_video", ""),
    (86, "Polish Photo Editor Mod", "photo_video", ""),
    (87, "A Color Story Mod", "photo_video", ""),
    (88, "Afterlight Mod", "photo_video", ""),
    (89, "Hypic Mod", "photo_video", ""),
    (90, "Foodie Mod", "photo_video", ""),
    (91, "Cymera Pro Mod", "photo_video", ""),
    (92, "Camera360 VIP Mod", "photo_video", ""),
    (93, "Open Camera Mod", "photo_video", ""),
    (94, "Footej Camera Pro Mod", "photo_video", ""),
    (95, "Camera FV-5 Pro Mod", "photo_video", ""),
    (96, "ProShot Pro Mod", "photo_video", ""),
    (97, "Halide Mark II Mod", "photo_video", ""),
    (98, "NeuralCam Pro Mod", "photo_video", ""),
    (99, "Spectre Camera Mod", "photo_video", ""),
    (100, "NOMO CAM Mod", "photo_video", ""),

    # ===== 3. HỌC TẬP & ĐỌC SÁCH (50 app) =====
    (101, "Duolingo Plus Mod", "education", ""),
    (102, "Quizlet Plus Mod", "education", ""),
    (103, "AnkiDroid Premium Mod", "education", ""),
    (104, "Photomath Plus Mod", "education", ""),
    (105, "Symbolab Pro Mod", "education", ""),
    (106, "Mathway Premium Mod", "education", ""),
    (107, "WolframAlpha Pro Mod", "education", ""),
    (108, "Gauthmath Mod", "education", ""),
    (109, "Socratic by Google Mod", "education", ""),
    (110, "Khan Academy Mod", "education", ""),
    (111, "Brilliant Premium Mod", "education", ""),
    (112, "SoloLearn Pro Mod", "education", ""),
    (113, "Mimo Premium Mod", "education", ""),
    (114, "Programming Hub Pro", "education", ""),
    (115, "Enki Premium Mod", "education", ""),
    (116, "edX Mod", "education", ""),
    (117, "Coursera Mod", "education", ""),
    (118, "Udemy Mod", "education", ""),
    (119, "Rosetta Stone Mod", "education", ""),
    (120, "Babbel Premium Mod", "education", ""),
    (121, "Memrise Pro Mod", "education", ""),
    (122, "Busuu Premium Mod", "education", ""),
    (123, "Lingodeer Premium Mod", "education", ""),
    (124, "Drops Premium Mod", "education", ""),
    (125, "Mondly Premium Mod", "education", ""),
    (126, "HelloTalk VIP Mod", "education", ""),
    (127, "Tandem Premium Mod", "education", ""),
    (128, "Moon+ Reader Pro Mod", "education", ""),
    (129, "ReadEra Premium Mod", "education", ""),
    (130, "Lithium Pro Mod", "education", ""),
    (131, "FBReader Premium Mod", "education", ""),
    (132, "Kindle Premium Mod", "education", ""),
    (133, "Google Play Books Mod", "education", ""),
    (134, "Scribd Mod", "education", ""),
    (135, "Audible Mod", "education", ""),
    (136, "Wattpad Premium Mod", "education", ""),
    (137, "Webnovel Mod", "education", ""),
    (138, "Dreame Premium Mod", "education", ""),
    (139, "GoodNovel Mod", "education", ""),
    (140, "Galatea Mod", "education", ""),
    (141, "Radish Mod", "education", ""),
    (142, "INKITT Mod", "education", ""),
    (143, "AnyBooks Mod", "education", ""),
    (144, "PDF Reader Pro Mod", "education", ""),
    (145, "Xodo PDF Reader Pro Mod", "education", ""),
    (146, "Adobe Acrobat Reader Pro Mod", "education", ""),
    (147, "CamScanner Pro Mod", "education", ""),
    (148, "Adobe Scan Premium Mod", "education", ""),
    (149, "Office Lens Mod", "education", ""),
    (150, "Notebloc Scanner Pro", "education", ""),

    # ===== 4. GAME OFFLINE MOD (100 app) =====
    # A. Game Casual & Giải đố
    (151, "Minecraft PE Mod", "games", "casual"),
    (152, "Stardew Valley Mod", "games", "casual"),
    (153, "Terraria Mod", "games", "casual"),
    (154, "Dead Cells Mod", "games", "casual"),
    (155, "Slay the Spire Mod", "games", "casual"),
    (156, "Monument Valley Full", "games", "casual"),
    (157, "GRIS Mod", "games", "casual"),
    (158, "Sky Children of Light Mod", "games", "casual"),
    (159, "The Room Full", "games", "casual"),
    (160, "Limbo Full", "games", "casual"),
    (161, "Inside Full", "games", "casual"),
    (162, "Badland Mod", "games", "casual"),
    (163, "Don't Starve Mod", "games", "casual"),
    (164, "Crashlands Mod", "games", "casual"),
    (165, "Oceanhorn Mod", "games", "casual"),
    (166, "Evoland 2 Mod", "games", "casual"),
    (167, "Titan Quest Mod", "games", "casual"),
    (168, "Kingdom Rush Mod", "games", "casual"),
    (169, "Plague Inc Mod", "games", "casual"),
    (170, "Rebel Inc Mod", "games", "casual"),
    (171, "Papers Please Mod", "games", "casual"),
    (172, "This War of Mine Mod", "games", "casual"),
    (173, "80 Days Mod", "games", "casual"),
    (174, "Samorost 3 Mod", "games", "casual"),
    (175, "Machinarium Mod", "games", "casual"),
    (176, "Botanicula Mod", "games", "casual"),
    (177, "Chuchel Mod", "games", "casual"),
    (178, "Creaks Mod", "games", "casual"),
    (179, "Rusty Lake Series Mod", "games", "casual"),
    (180, "Cube Escape Mod", "games", "casual"),
    # B. Game Hành động & RPG
    (181, "Oddmar Mod", "games", "action_rpg"),
    (182, "Leo's Fortune Mod", "games", "action_rpg"),
    (183, "Grimvalor Mod", "games", "action_rpg"),
    (184, "Pascal's Wager Mod", "games", "action_rpg"),
    (185, "Implosion Mod", "games", "action_rpg"),
    (186, "ICEY Mod", "games", "action_rpg"),
    (187, "Soul Knight Mod", "games", "action_rpg"),
    (188, "Otherworld Legends Mod", "games", "action_rpg"),
    (189, "Archero Mod", "games", "action_rpg"),
    (190, "Dan the Man Mod", "games", "action_rpg"),
    (191, "BombSquad Mod", "games", "action_rpg"),
    (192, "SuperTuxKart Mod", "games", "action_rpg"),
    (193, "OpenTTD Mod", "games", "action_rpg"),
    (194, "Unciv Mod", "games", "action_rpg"),
    (195, "Mini Metro Mod", "games", "action_rpg"),
    (196, "Poly Bridge Mod", "games", "action_rpg"),
    (197, "Human Fall Flat Mod", "games", "action_rpg"),
    (198, "Crash of Cars Mod", "games", "action_rpg"),
    (199, "Data Wing Mod", "games", "action_rpg"),
    (200, "Downwell Mod", "games", "action_rpg"),
    # C. Game Simulation & Strategy
    (201, "RollerCoaster Tycoon Classic Mod", "games", "simulation"),
    (202, "Project Highrise Mod", "games", "simulation"),
    (203, "The Escapists Mod", "games", "simulation"),
    (204, "Prison Architect Mod", "games", "simulation"),
    (205, "Mini Motorways Mod", "games", "simulation"),
    (206, "Islanders Mod", "games", "simulation"),
    (207, "Townscaper Mod", "games", "simulation"),
    (208, "The Battle of Polytopia Mod", "games", "simulation"),
    (209, "Reigns Mod", "games", "simulation"),
    (210, "Card Thief Mod", "games", "simulation"),
    (211, "Meteorfall Mod", "games", "simulation"),
    (212, "Night of the Full Moon Mod", "games", "simulation"),
    (213, "Dungeon Faster Mod", "games", "simulation"),
    (214, "Pirate Outlaws Mod", "games", "simulation"),
    (215, "Dicey Dungeons Mod", "games", "simulation"),
    # D. Game Board & Cờ
    (216, "Chess Premium Mod", "games", "board"),
    (217, "Really Bad Chess Mod", "games", "board"),
    (218, "Lichess Mod", "games", "board"),
    (219, "Monopoly Mod", "games", "board"),
    (220, "Carcassonne Mod", "games", "board"),
    (221, "Ticket to Ride Mod", "games", "board"),
    (222, "Catan Classic Mod", "games", "board"),
    (223, "Agricola Mod", "games", "board"),
    (224, "Patchwork Mod", "games", "board"),
    (225, "Splendor Mod", "games", "board"),
    # E. Game Offline Nhẹ
    (226, "Alto's Odyssey Mod", "games", "light"),
    (227, "Crossy Road Mod", "games", "light"),
    (228, "Doodle Jump Mod", "games", "light"),
    (229, "Jetpack Joyride Mod", "games", "light"),
    (230, "Fruit Ninja Mod", "games", "light"),
    (231, "Cut the Rope Mod", "games", "light"),
    (232, "Angry Birds Mod", "games", "light"),
    (233, "Plants vs Zombies Mod", "games", "light"),
    (234, "Subway Surfers Mod", "games", "light"),
    (235, "Temple Run 2 Mod", "games", "light"),
    (236, "Hill Climb Racing Mod", "games", "light"),
    (237, "Zombie Tsunami Mod", "games", "light"),
    (238, "Hungry Shark Evolution Mod", "games", "light"),
    (239, "Vector Mod", "games", "light"),
    (240, "Smash Hit Mod", "games", "light"),
    (241, "BBTAN Mod", "games", "light"),
    (242, "Ballz Mod", "games", "light"),
    (243, "Stack Ball Mod", "games", "light"),
    (244, "Helix Jump Mod", "games", "light"),
    (245, "Color Road Mod", "games", "light"),
    (246, "Circle Rush Mod", "games", "light"),
    (247, "Piano Tiles 2 Mod", "games", "light"),
    (248, "Magic Tiles 3 Mod", "games", "light"),
    (249, "Beat Blade Mod", "games", "light"),
    (250, "Dancing Road Mod", "games", "light"),

    # ===== 5. CÔNG CỤ & TIỆN ÍCH (100 app) =====
    # A. File & Quản lý hệ thống
    (251, "Solid Explorer Pro Mod", "tools", "file_manager"),
    (252, "MiXplorer Silver Mod", "tools", "file_manager"),
    (253, "FX File Explorer Pro", "tools", "file_manager"),
    (254, "Total Commander Mod", "tools", "file_manager"),
    (255, "X-plore Pro Mod", "tools", "file_manager"),
    (256, "Amaze File Manager Mod", "tools", "file_manager"),
    (257, "Material Files Pro", "tools", "file_manager"),
    (258, "File Manager+ Pro", "tools", "file_manager"),
    (259, "ES File Explorer Pro Mod", "tools", "file_manager"),
    (260, "ASTRO File Manager Pro", "tools", "file_manager"),
    (261, "Cx File Explorer Pro", "tools", "file_manager"),
    (262, "File Expert Pro Mod", "tools", "file_manager"),
    # B. Mạng & VPN
    (263, "ExpressVPN Mod", "tools", "vpn"),
    (264, "NordVPN Mod", "tools", "vpn"),
    (265, "Surfshark Mod", "tools", "vpn"),
    (266, "Windscribe Mod", "tools", "vpn"),
    (267, "ProtonVPN Mod", "tools", "vpn"),
    (268, "Hotspot Shield Mod", "tools", "vpn"),
    (269, "Turbo VPN Mod", "tools", "vpn"),
    (270, "Thunder VPN Mod", "tools", "vpn"),
    (271, "VPN 360 Mod", "tools", "vpn"),
    (272, "Psiphon Pro Mod", "tools", "vpn"),
    (273, "Betternet Mod", "tools", "vpn"),
    (274, "Hide.me VPN Mod", "tools", "vpn"),
    (275, "VyprVPN Mod", "tools", "vpn"),
    (276, "ZenMate VPN Mod", "tools", "vpn"),
    (277, "TunnelBear Mod", "tools", "vpn"),
    (278, "AdGuard VPN Mod", "tools", "vpn"),
    # C. Tiện ích hệ thống
    (279, "SD Maid Pro Mod", "tools", "system"),
    (280, "CCleaner Pro Mod", "tools", "system"),
    (281, "AVG Cleaner Pro Mod", "tools", "system"),
    (282, "All-in-One Toolbox Mod", "tools", "system"),
    (283, "Nox Cleaner Mod", "tools", "system"),
    (284, "Clean Master Pro Mod", "tools", "system"),
    (285, "Phone Cleaner Pro Mod", "tools", "system"),
    (286, "Storage Cleaner Pro Mod", "tools", "system"),
    (287, "Battery Guru Pro Mod", "tools", "system"),
    (288, "AccuBattery Pro Mod", "tools", "system"),
    (289, "GSam Battery Monitor Pro", "tools", "system"),
    (290, "Greenify Donate Mod", "tools", "system"),
    (291, "Naptime Mod", "tools", "system"),
    (292, "Brevent Mod", "tools", "system"),
    (293, "Servicely Mod", "tools", "system"),
    (294, "L Speed Mod", "tools", "system"),
    (295, "Kernel Adiutor Mod", "tools", "system"),
    (296, "Franco Kernel Manager Mod", "tools", "system"),
    (297, "EX Kernel Manager Mod", "tools", "system"),
    (298, "CPU Monitor Pro Mod", "tools", "system"),
    (299, "Device Info HW Pro Mod", "tools", "system"),
    (300, "AIDA64 Pro Mod", "tools", "system"),
    # D. Sao lưu & Khôi phục
    (301, "Titanium Backup Pro Mod", "tools", "backup"),
    (302, "Swift Backup Pro Mod", "tools", "backup"),
    (303, "Migrate Custom ROM Mod", "tools", "backup"),
    (304, "Backup & Restore Pro Mod", "tools", "backup"),
    (305, "SMS Backup & Restore Pro", "tools", "backup"),
    (306, "Call Log Backup Pro", "tools", "backup"),
    (307, "Contacts Backup Pro", "tools", "backup"),
    (308, "Calendar Backup Pro", "tools", "backup"),
    (309, "Photos Backup Pro", "tools", "backup"),
    (310, "Videos Backup Pro", "tools", "backup"),
    (311, "Music Backup Pro", "tools", "backup"),
    (312, "Documents Backup Pro", "tools", "backup"),
    (313, "Files Backup Pro", "tools", "backup"),
    (314, "App Backup & Restore Pro", "tools", "backup"),
    (315, "System Backup Pro", "tools", "backup"),
    (316, "Full Backup Pro", "tools", "backup"),
    (317, "Auto Backup Pro", "tools", "backup"),
    (318, "Cloud Backup Pro", "tools", "backup"),
    (319, "Local Backup Pro", "tools", "backup"),
    (320, "SD Card Backup Pro", "tools", "backup"),
    # E. Công cụ đa năng
    (321, "Calculator++ Pro Mod", "tools", "utility"),
    (322, "HiPER Calc Pro Mod", "tools", "utility"),
    (323, "RealCalc Plus Mod", "tools", "utility"),
    (324, "MyScript Calculator Pro", "tools", "utility"),
    (325, "Period Calendar Pro Mod", "tools", "utility"),
    (326, "Flo Period Tracker Mod", "tools", "utility"),
    (327, "Clue Period Tracker Mod", "tools", "utility"),
    (328, "Eve Period Tracker Mod", "tools", "utility"),
    (329, "Spotify Equalizer Pro Mod", "tools", "utility"),
    (330, "Wavelet Pro Mod", "tools", "utility"),
    (331, "Equalizer FX Pro Mod", "tools", "utility"),
    (332, "Bass Booster Pro Mod", "tools", "utility"),
    (333, "Volume Booster Pro Mod", "tools", "utility"),
    (334, "Precise Volume Pro Mod", "tools", "utility"),
    (335, "Volume Styles Pro Mod", "tools", "utility"),
    (336, "Custom Volume Panel Pro", "tools", "utility"),
    (337, "Ringtones & Wallpapers Pro", "tools", "utility"),
    (338, "Zedge Premium Mod", "tools", "utility"),
    (339, "Walli 4K Premium Mod", "tools", "utility"),
    (340, "Backdrops Premium Mod", "tools", "utility"),
    (341, "Resplash Premium Mod", "tools", "utility"),
    (342, "Pixwall Premium Mod", "tools", "utility"),
    (343, "Wallcraft Premium Mod", "tools", "utility"),
    (344, "Wallrox Premium Mod", "tools", "utility"),
    (345, "Wallpapers Central Premium", "tools", "utility"),
    (346, "Wallpaper Studio Premium", "tools", "utility"),
    (347, "Wallpaper HD Premium Mod", "tools", "utility"),
    (348, "Wallpaper 3D Premium Mod", "tools", "utility"),
    (349, "Live Wallpaper Premium Mod", "tools", "utility"),
    (350, "KLWP Kustom Wallpaper Pro", "tools", "utility"),

    # ===== 6. VĂN PHÒNG & NĂNG SUẤT (50 app) =====
    (351, "Microsoft Office Mod", "office", ""),
    (352, "WPS Office Premium Mod", "office", ""),
    (353, "Polaris Office Pro Mod", "office", ""),
    (354, "Smart Office 2 Pro Mod", "office", ""),
    (355, "OfficeSuite Premium Mod", "office", ""),
    (356, "Google Docs Mod", "office", ""),
    (357, "Notion Premium Mod", "office", ""),
    (358, "Evernote Premium Mod", "office", ""),
    (359, "OneNote Premium Mod", "office", ""),
    (360, "Google Keep Mod", "office", ""),
    (361, "Bear Notes Pro Mod", "office", ""),
    (362, "Simplenote Pro Mod", "office", ""),
    (363, "Standard Notes Pro Mod", "office", ""),
    (364, "Joplin Premium Mod", "office", ""),
    (365, "Zoho Notebook Pro Mod", "office", ""),
    (366, "ColorNote Pro Mod", "office", ""),
    (367, "TickTick Premium Mod", "office", ""),
    (368, "Todoist Pro Mod", "office", ""),
    (369, "Microsoft To Do Mod", "office", ""),
    (370, "Any.do Premium Mod", "office", ""),
    (371, "Habitica Premium Mod", "office", ""),
    (372, "HabitBull Pro Mod", "office", ""),
    (373, "Loop Habit Tracker Pro", "office", ""),
    (374, "Forest Premium Mod", "office", ""),
    (375, "Flora Premium Mod", "office", ""),
    (376, "Focus To-Do Premium Mod", "office", ""),
    (377, "Pomodoro Timer Pro Mod", "office", ""),
    (378, "Be Focused Pro Mod", "office", ""),
    (379, "Focus Plant Pro Mod", "office", ""),
    (380, "Tide Premium Mod", "office", ""),
    (381, "Noisli Premium Mod", "office", ""),
    (382, "My Noise Pro Mod", "office", ""),
    (383, "White Noise Pro Mod", "office", ""),
    (384, "Relax Melodies Premium Mod", "office", ""),
    (385, "Rain Rain Premium Mod", "office", ""),
    (386, "Sleep Sounds Premium Mod", "office", ""),
    (387, "Pzizz Premium Mod", "office", ""),
    (388, "Sleep Cycle Premium Mod", "office", ""),
    (389, "Pillow Premium Mod", "office", ""),
    (390, "Sleep as Android Premium", "office", ""),
    (391, "SnoreLab Premium Mod", "office", ""),
    (392, "Sleep Score Premium Mod", "office", ""),
    (393, "Sleepzy Premium Mod", "office", ""),
    (394, "Sleep Timer Premium Mod", "office", ""),
    (395, "Deep Sleep Premium Mod", "office", ""),
    (396, "Calm Premium Mod", "office", ""),
    (397, "Headspace Premium Mod", "office", ""),
    (398, "Insight Timer Premium Mod", "office", ""),
    (399, "Smiling Mind Pro Mod", "office", ""),
    (400, "Breethe Premium Mod", "office", ""),

    # ===== 7. BẢN ĐỒ & DU LỊCH (30 app) =====
    (401, "MAPS.ME Pro Mod", "travel", ""),
    (402, "OsmAnd+ Premium Mod", "travel", ""),
    (403, "Organic Maps Premium Mod", "travel", ""),
    (404, "Guru Maps Pro Mod", "travel", ""),
    (405, "Locus Map Pro Mod", "travel", ""),
    (406, "Sygic GPS Navigation Mod", "travel", ""),
    (407, "HERE WeGo Mod", "travel", ""),
    (408, "TomTom GO Navigation Mod", "travel", ""),
    (409, "CoPilot GPS Navigation Mod", "travel", ""),
    (410, "Navmii GPS Navigation Mod", "travel", ""),
    (411, "Magic Earth Pro Mod", "travel", ""),
    (412, "Citymapper Premium Mod", "travel", ""),
    (413, "Moovit Premium Mod", "travel", ""),
    (414, "Transit App Premium Mod", "travel", ""),
    (415, "TripIt Pro Mod", "travel", ""),
    (416, "TripAdvisor Premium Mod", "travel", ""),
    (417, "Booking.com Mod", "travel", ""),
    (418, "Airbnb Mod", "travel", ""),
    (419, "Agoda Mod", "travel", ""),
    (420, "Hotels.com Mod", "travel", ""),
    (421, "Expedia Mod", "travel", ""),
    (422, "Trivago Mod", "travel", ""),
    (423, "Skyscanner Mod", "travel", ""),
    (424, "Kayak Mod", "travel", ""),
    (425, "Hopper Mod", "travel", ""),
    (426, "PackPoint Premium Mod", "travel", ""),
    (427, "Roadtrippers Premium Mod", "travel", ""),
    (428, "Polarsteps Pro Mod", "travel", ""),
    (429, "TravelSpend Pro Mod", "travel", ""),
    (430, "XE Currency Pro Mod", "travel", ""),

    # ===== 8. SỨC KHỎE & THỂ THAO (40 app) =====
    (431, "MyFitnessPal Premium Mod", "health", ""),
    (432, "Lose It Premium Mod", "health", ""),
    (433, "FatSecret Premium Mod", "health", ""),
    (434, "Cronometer Premium Mod", "health", ""),
    (435, "YAZIO Premium Mod", "health", ""),
    (436, "Fooducate Premium Mod", "health", ""),
    (437, "Lifesum Premium Mod", "health", ""),
    (438, "Noom Premium Mod", "health", ""),
    (439, "WW Weight Watchers Mod", "health", ""),
    (440, "Step Counter Pro Mod", "health", ""),
    (441, "Pedometer Pro Mod", "health", ""),
    (442, "Accupedo Pro Mod", "health", ""),
    (443, "Pacer Pedometer Pro", "health", ""),
    (444, "WalkTracker Pro Mod", "health", ""),
    (445, "Fitbit Mod", "health", ""),
    (446, "Samsung Health Mod", "health", ""),
    (447, "Google Fit Mod", "health", ""),
    (448, "Huawei Health Mod", "health", ""),
    (449, "Mi Fit Mod", "health", ""),
    (450, "Zepp Life Mod", "health", ""),
    (451, "Strava Premium Mod", "health", ""),
    (452, "Runkeeper Pro Mod", "health", ""),
    (453, "Runtastic Pro Mod", "health", ""),
    (454, "Endomondo Premium Mod", "health", ""),
    (455, "MapMyRun Premium Mod", "health", ""),
    (456, "Nike Run Club Mod", "health", ""),
    (457, "Adidas Running Mod", "health", ""),
    (458, "7 Minute Workout Pro Mod", "health", ""),
    (459, "30 Day Fitness Pro Mod", "health", ""),
    (460, "Home Workout Pro Mod", "health", ""),
    (461, "Nike Training Club Mod", "health", ""),
    (462, "Adidas Training Mod", "health", ""),
    (463, "Freeletics Mod", "health", ""),
    (464, "Fitbod Mod", "health", ""),
    (465, "JEFIT Pro Mod", "health", ""),
    (466, "Strong Pro Mod", "health", ""),
    (467, "Gym Workout Pro Mod", "health", ""),
    (468, "Daily Yoga Pro Mod", "health", ""),
    (469, "Down Dog Yoga Pro Mod", "health", ""),
    (470, "5 Minute Yoga Pro Mod", "health", ""),

    # ===== 9. CÔNG CỤ MOD & HACK (29 app) =====
    (471, "Lucky Patcher", "mod_tools", ""),
    (472, "GameGuardian", "mod_tools", ""),
    (473, "APK Editor Pro Mod", "mod_tools", ""),
    (474, "MT Manager Mod", "mod_tools", ""),
    (475, "NP Manager Mod", "mod_tools", ""),
    (476, "Apktool M Mod", "mod_tools", ""),
    (477, "VirtualXposed", "mod_tools", ""),
    (478, "TaiChi", "mod_tools", ""),
    (479, "Parallel Space VIP Mod", "mod_tools", ""),
    (480, "Multi Parallel Mod", "mod_tools", ""),
    (481, "App Cloner Premium Mod", "mod_tools", ""),
    (482, "Island Mod", "mod_tools", ""),
    (483, "Shelter Mod", "mod_tools", ""),
    (484, "Dual Space Mod", "mod_tools", ""),
    (485, "Super Clone Mod", "mod_tools", ""),
    (486, "2Accounts Pro Mod", "mod_tools", ""),
    (487, "Accounts Manager Pro Mod", "mod_tools", ""),
    (488, "User Manager Pro Mod", "mod_tools", ""),
    (489, "Profile Manager Pro Mod", "mod_tools", ""),
    (490, "Phone Clone Pro Mod", "mod_tools", ""),
    (491, "Data Transfer Pro Mod", "mod_tools", ""),
    (492, "WiFi Password Recovery Pro", "mod_tools", ""),
    (493, "WiFi Key Recovery Pro", "mod_tools", ""),
    (494, "WiFi Analyzer Pro Mod", "mod_tools", ""),
    (495, "Network Signal Guru Pro", "mod_tools", ""),
    (496, "GPS Status & Toolbox Pro", "mod_tools", ""),
    (497, "Satellite Tracker Pro", "mod_tools", ""),
    (498, "Astronomy Tools Pro", "mod_tools", ""),
    (499, "Sky Map Pro Mod", "mod_tools", ""),
]

CATEGORY_NAMES = {
    'streaming': 'Phim Nhạc & Streaming',
    'photo_video': 'Chỉnh Sửa Ảnh & Video',
    'education': 'Học Tập & Đọc Sách',
    'games': 'Game Offline Mod',
    'tools': 'Công Cụ & Tiện Ích',
    'office': 'Văn Phòng & Năng Suất',
    'travel': 'Bản Đồ & Du Lịch',
    'health': 'Sức Khỏe & Thể Thao',
    'mod_tools': 'Công Cụ Mod & Hack',
}

def make_slug(name):
    s = name.lower()
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')

def make_search_keywords(name):
    """Generate search keywords for APK mod sites"""
    base = re.sub(r'\s*(Mod|Pro|Premium|VIP|Full|Gold|Diamond|Plus|Lite)\s*', ' ', name).strip()
    base = re.sub(r'\s+', ' ', base)
    keywords = [name, base, base + " mod apk", base + " premium apk"]
    return list(dict.fromkeys(keywords))  # deduplicate

def generate():
    apps = []
    for app_id, name, category, subcategory in APPS:
        apps.append({
            "id": app_id,
            "name": name,
            "slug": make_slug(name),
            "category": category,
            "category_name": CATEGORY_NAMES[category],
            "subcategory": subcategory,
            "search_keywords": make_search_keywords(name),
            "package_name": "",
            "version": "",
            "size": "",
            "icon_url": "",
            "description_vi": "",
            "download_url": "",
            "apk_file": "",
            "telegram_file_id": "",
            "r2_url": "",
            "status": "pending",
            "last_updated": ""
        })
    
    out_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'apps_list.json')
    out_path = os.path.abspath(out_path)
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump({"total": len(apps), "apps": apps}, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(apps)} apps -> {out_path}")

if __name__ == '__main__':
    generate()
