create table if not exists apps (
  id bigint generated by default as identity primary key,
  app_id text,
  title text,
  icon text,
  description text,
  telegram_link text,
  date timestamptz,
  unique (app_id, date)
);
